services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://epify_user:epify_password@db:5432/epify_db}"
      JWT_SECRET: "${JWT_SECRET:-please-set-jwt-secret-in-env-file}"
      NEXT_PUBLIC_APP_URL: "${NEXT_PUBLIC_APP_URL:-http://localhost:3000}"
      NODE_ENV: "${NODE_ENV:-development}"
    depends_on:
      - db
    networks:
      - epify-network
    # Load environment variables from .env file
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-epify_db}"
      POSTGRES_USER: "${POSTGRES_USER:-epify_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-epify_password}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - epify-network
    # Load environment variables from .env file
    env_file:
      - .env

networks:
  epify-network:
    driver: bridge

volumes:
  db_data: